// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpsBoard.Infrastructure.Persistence;

#nullable disable

namespace OpsBoard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpsBoardDbContext))]
    partial class OpsBoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpsBoard.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<long>("LastHistorySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_history_sequence");

                    b.Property<long>("LifecycleVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("lifecycle_version");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedByUserId")
                        .HasDatabaseName("ix_incidents_organization_created_by_user");

                    b.HasIndex("OrganizationId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_incidents_organization_created_at_id");

                    b.HasIndex("OrganizationId", "ServiceId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_incidents_organization_service_created_at_id");

                    b.HasIndex("OrganizationId", "Severity", "CreatedAt", "Id")
                        .HasDatabaseName("ix_incidents_organization_severity_created_at_id");

                    b.HasIndex("OrganizationId", "Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_incidents_organization_status_created_at_id");

                    b.ToTable("incidents", null, t =>
                        {
                            t.HasCheckConstraint("ck_incidents_description_nonblank", "char_length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_incidents_last_history_sequence_nonnegative", "last_history_sequence >= 0");

                            t.HasCheckConstraint("ck_incidents_lifecycle_version_positive", "lifecycle_version >= 1");

                            t.HasCheckConstraint("ck_incidents_resolved_at_matches_status", "(status = 'Resolved' AND resolved_at IS NOT NULL AND resolved_at >= created_at AND resolved_at <= updated_at)\nOR (status <> 'Resolved' AND resolved_at IS NULL)");

                            t.HasCheckConstraint("ck_incidents_severity", "severity IN ('Critical','High','Medium','Low')");

                            t.HasCheckConstraint("ck_incidents_status", "status IN ('Investigating','Identified','Monitoring','Resolved')");

                            t.HasCheckConstraint("ck_incidents_title_nonblank", "char_length(btrim(title)) > 0");

                            t.HasCheckConstraint("ck_incidents_updated_after_created", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_incidents_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.IncidentResponder", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("IncidentId", "UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_incident_responders_organization_user");

                    b.HasIndex("OrganizationId", "IncidentId", "UserId")
                        .HasDatabaseName("ix_incident_responders_organization_incident_user");

                    b.ToTable("incident_responders", (string)null);
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.IncidentTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<string>("FromSeverity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_severity");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("ToSeverity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_severity");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_timeline_incident_sequence");

                    b.HasIndex("OrganizationId", "ActorUserId")
                        .HasDatabaseName("ix_timeline_organization_actor");

                    b.HasIndex("OrganizationId", "IncidentId", "OccurredAt", "Sequence")
                        .HasDatabaseName("ix_timeline_organization_incident_occurred_sequence");

                    b.ToTable("incident_timeline_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_timeline_payload", "(type = 'IncidentCreated' AND body IS NULL AND from_status IS NULL AND to_status = 'Investigating' AND from_severity IS NULL AND to_severity IS NOT NULL)\nOR (type = 'StatusChanged' AND body IS NULL AND from_status IS NOT NULL AND to_status IS NOT NULL AND from_status <> to_status AND from_status IN ('Investigating','Identified','Monitoring') AND to_status IN ('Investigating','Identified','Monitoring') AND from_severity IS NULL AND to_severity IS NULL)\nOR (type = 'SeverityChanged' AND body IS NULL AND from_status IS NULL AND to_status IS NULL AND from_severity IS NOT NULL AND to_severity IS NOT NULL AND from_severity <> to_severity)\nOR (type IN ('ResponderJoined','ResponderLeft') AND body IS NULL AND from_status IS NULL AND to_status IS NULL AND from_severity IS NULL AND to_severity IS NULL)\nOR (type = 'Resolved' AND body IS NULL AND from_status IN ('Investigating','Identified','Monitoring') AND to_status = 'Resolved' AND from_severity IS NULL AND to_severity IS NULL)\nOR (type = 'Reopened' AND body IS NULL AND from_status = 'Resolved' AND to_status = 'Investigating' AND from_severity IS NULL AND to_severity IS NULL)\nOR (type = 'WrittenUpdate' AND body IS NOT NULL AND char_length(btrim(body)) > 0 AND from_status IS NULL AND to_status IS NULL AND from_severity IS NULL AND to_severity IS NULL)");

                            t.HasCheckConstraint("ck_timeline_sequence_positive", "sequence >= 1");

                            t.HasCheckConstraint("ck_timeline_type", "type IN ('IncidentCreated','StatusChanged','SeverityChanged','ResponderJoined','ResponderLeft','Resolved','Reopened','WrittenUpdate')");
                        });
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_name_nonblank", "char_length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Postmortem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("impact");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("resolution");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("root_cause");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("summary");

                    b.PrimitiveCollection<List<string>>("_actionItems")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("action_items");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_postmortems_organization_incident");

                    b.ToTable("postmortems", null, t =>
                        {
                            t.HasCheckConstraint("ck_postmortems_action_items_cardinality", "cardinality(action_items) BETWEEN 1 AND 20");

                            t.HasCheckConstraint("ck_postmortems_impact_nonblank", "char_length(btrim(impact)) > 0");

                            t.HasCheckConstraint("ck_postmortems_resolution_nonblank", "char_length(btrim(resolution)) > 0");

                            t.HasCheckConstraint("ck_postmortems_root_cause_nonblank", "char_length(btrim(root_cause)) > 0");

                            t.HasCheckConstraint("ck_postmortems_summary_nonblank", "char_length(btrim(summary)) > 0");
                        });
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Health", "Id")
                        .HasDatabaseName("ix_services_organization_health_id");

                    b.HasIndex("OrganizationId", "Name", "Id")
                        .HasDatabaseName("ix_services_organization_name_id");

                    b.HasIndex("OrganizationId", "TeamId", "Id")
                        .HasDatabaseName("ix_services_organization_team_id");

                    b.ToTable("services", null, t =>
                        {
                            t.HasCheckConstraint("ck_services_description_nonblank", "char_length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_services_health", "health IN ('Operational','Degraded','Outage')");

                            t.HasCheckConstraint("ck_services_name_nonblank", "char_length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_services_updated_after_created", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_services_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.ToTable("teams", null, t =>
                        {
                            t.HasCheckConstraint("ck_teams_name_nonblank", "char_length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "TeamId", "Id")
                        .HasDatabaseName("ix_users_organization_team_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_display_name_nonblank", "char_length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_users_role", "role IN ('Viewer','Responder','IncidentManager','Administrator')");
                        });
                });

            modelBuilder.Entity("OpsBoard.Infrastructure.Persistence.Seed.DemoSeedRun", b =>
                {
                    b.Property<string>("SeedKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("seed_key");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FixtureVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fixture_version");

                    b.HasKey("SeedKey");

                    b.ToTable("demo_seed_runs", (string)null);
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Incident", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ServiceId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.IncidentResponder", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.Incident", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "IncidentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.IncidentTimelineEntry", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.Incident", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "IncidentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Postmortem", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.Incident", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "IncidentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Service", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.Team", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpsBoard.Domain.Entities.User", b =>
                {
                    b.HasOne("OpsBoard.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpsBoard.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
